### ISSUE TITLE
Entity spawning / hittrace override through portals

### ISSUE THREAD

**Issue by MysteryPancake** [MattJeanes/world-portals#12]
[This image describes what I am trying to suggest](https://steamuserimages-a.akamaihd.net/ugc/778406850968770138/A2D0EC29C374E3AB79C67EE9BD88B8029E6334DA/)
Currently, if you are looking through the Tardis doors and you try to spawn an entity, it doesn't spawn it inside the Tardis. It spawns on the Tardis entity. This is perfectly understandable, but it would add realism if you could detour this function to change the position to the Tardis interior. You appear to already have detoured the bullet functions so if you shoot into the Tardis the bullets end up there, so it may be possible to do this as well.

**Comment by MattJeanes** [comment]
Transferred to world-portals as this would be a more generic hittrace override through portals

**Comment by MattJeanes** [comment]
Done in #17 and #18
