### ISSUE TITLE
Hammer integration

### ISSUE THREAD

**Issue by kaonashi696** [MattJeanes/world-portals#16]
I'm trying to use this on Hammer for a gmod map, is that posible?

**Comment by candee249** [comment]
Yes thats why its there

**Comment by MattJeanes** [comment]
Yep absolutely, there is a fgd file in this repository you can import into hammer and it allows you to place down and configure linked_portal_door entities, the users will need to have this add-on installed (recommend asking them to subscribe to the Doors add-on on workshop)
