### ISSUE TITLE
World portals and SB_omen_v2 dont mix

### ISSUE THREAD

**Issue by Shigbeard** [MattJeanes/world-portals#3]
Sorry for the terrible title, I sat here for 30 minutes thinking about it and came up with nothing better. When using any of your addons that use world-portals and doors, this bug will appear (most notably with SB_omen_v2).

In SB_Omen_v2, planets have an internal "sky", which changes regularly based on some logic_relays. This is what it is supposed to look like. I've set up a wire contraption to open/close the doors of a TARDIS when I press a key on my keyboard for this purpose.

![Doors closed: Sky renders.](https://i.sli.mg/PCcLCh.png)

When the TARDIS doors are shut and the world portal is not being rendered, the sky is being rendered normally. However, if I were to open the doors...

![Doors open: Sky disappears](https://i.sli.mg/LmuC6U.jpg)

To further prove that it is the rendering of the world portal, I walked around the TARDIS until the open doors could not be seen. The sky immediately begins to render once the portal is out of eyesight.

![Behind TARDIS, sky is here](https://i.sli.mg/FmfZU7.png)

This also happens with Safespace, not just the Tardis, although with Safespace it is harder to reproduce.

![Sometimes it removes the sky...](https://i.sli.mg/c9JLN1.jpg)
![And sometimes it shows it...](https://i.sli.mg/fHkEAD.png)

Decompiling the map revealed to me that this sky is infact a func_occluder (whatever the fuck that is, im no mapper)...

![Hammer](https://i.sli.mg/KlSQUQ.png)

This may not be an issue with world-portals in particular, however Im posting here on a hunch that it has something to do with rendering the other side of the worldportal when the "real" other side is also in camera view. (Note the safespace inconsistency)

**Comment by benrob0329** [comment]
I think that the problem is with the LOD because on other maps (like gm_fork) decorations (like trees and signs) disappear within a certain radius.

**Comment by MattJeanes** [comment]
It's not something we can solve either way, we use `render.RenderView` to make the portal views, it's an engine issue and I cannot fix it unfortunately.
